### ISSUE TITLE
How to run migrations and mix tasks

### ISSUE THREAD

**Issue by zprima** [GoogleCloudPlatform/elixir-runtime#16]
How to run `mix ecto.migrate` command for example on app engine. Or is there another way that is more recommended?

Probably running `cloud_proxy` connect to the live db and run migration from local to there and then deploy the new release?

**Comment by alizain** [comment]
It's important to be able to do this automatically when the app deploys itself. Is there something in the `app.yaml` that we can use?

**Comment by dazuma** [comment]
@zprima @alizain 

It is _possible_ to add build tasks to the `app.yaml`. See the section on [customizing application builds](https://github.com/GoogleCloudPlatform/elixir-runtime/#customizing-application-builds) in the README.

However, I recommend running database migrations separately from your own CI workflow rather than use App Engine's build process. The reason is, you probably want more control over how and when the migration takes place, when it affects something like a database that is separate from App Engine itself.

If you do choose to customize the `app.yaml` to migrate your database, note there are some caveats.
1. If you're running phoenix, the Elixir runtime defaults this setting to do a brunch build, so if you override it, and you still want to brunch build, you have to add it yourself. (The section in the README details this.)
2. `mix ecto.migrate` needs access to your database. If you're using Google Cloud SQL, that means you will need the [cloud sql proxy](https://cloud.google.com/sql/docs/postgres/sql-proxy) which is not present in the build image by default. You will need to install it yourself, either by downloading it as one of your build tasks, or possibly by including it in your app's `/priv` directory. Ping me directly (@dazuma) if you get stuck on this, and I can provide some further guidance.

For Ruby, I created a rake task that runs database migrations in the cloud (so you don't need to install the cloud sql proxy yourself or deal with the risks of mucking with the production database directly from your workstation.) The workflow is to deploy to app engine without promoting the new version to current, then kick off the migration, then switch app engine to the new version. (See http://www.rubydoc.info/gems/appengine/AppEngine/Tasks for more details.) Let me know if you think a similar mix task would be helpful for your case.

**Comment by alizain** [comment]
> However, I recommend running database migrations separately from your own CI workflow rather than use App Engine's build process. 

I would agree.

I was looking for something like `pre_run_hooks` in this runtime, but realized soon after posting the earlier comment that `distillery` is designed to handle exactly these use-cases.

So that's what I used, and it works wonderfully well!

@zprima - check out these [docs](https://hexdocs.pm/distillery/running-migrations.html) to get started.

@dazuma - thanks for your help, and your detailed response! this runtime is great, and I hope it gets broad support at Google!

**Comment by dazuma** [comment]
Closing since there don't seem to be follow-up questions. Feel free to re-open if it's not clear.

**Comment by dustinfarris** [comment]
@alizain could you elaborate on:

> realized soon after posting the earlier comment that distillery is designed to handle exactly these use-cases.

How are you leveraging distillery to run migrations after a successful build/deploy?
