### ISSUE TITLE
Followed tutorial - Build Failed.

### ISSUE THREAD

**Issue by newterminator** [GoogleCloudPlatform/elixir-runtime#6]
![screen shot 2017-11-29 at 7 18 55 pm](https://user-images.githubusercontent.com/5087437/33406337-5434bbcc-d53a-11e7-8079-eaf654381d69.png)
I followed the tutorial listed at [https://cloud.google.com/community/tutorials/elixir-phoenix-on-google-app-engine](https://cloud.google.com/community/tutorials/elixir-phoenix-on-google-app-engine)

Following Step 2: and running 
$ gcloud app deploy
gave the above result. I attached a screenshot above.

**Comment by dazuma** [comment]
Hi, sorry about that. The build image had omitted a C compiler. The good news is you caught me right before releasing a major update that fixes this issue among a bunch of others (and some useful new features). The update is live as of this morning. Try a deployment now and see if it works better.

The README has been updated to reflect the new features (among them being support for building a Distillery release for deployment). The tutorial hasn't yet been updated, but it should still work as is.

**Comment by newterminator** [comment]
Hey @dazuma, Thank you so much for update. The deployment did succeed. 

Though I had one question. The tutorial omits ecto and guidelines in connecting the database. My app already has the database part. 

How would I get the Postgresql (Google Cloud Sql hosted instance) connected to this deployment.

**Comment by dazuma** [comment]
Unfortunately, it's still a bit difficult to connect a Cloud SQL postgres database, because App Engine wants to connect via a unix domain socket, and support for that isn't yet available in a released version of postgrex. You can probably depend on edge postgrex (i.e. get the dependency from github master rather than from hex). I know @chingor13 has [done this](https://github.com/chingor13/white_elephant/compare/gae) successfully; you might ask him if you get stuck. Or we should just get the Ecto team to cut a new postgrex release...

Once you get over that hurdle, you can use one of the existing appengine-postgres tutorials ([here's one for Ruby](https://cloud.google.com/appengine/docs/flexible/ruby/using-cloud-sql-postgres)) to get a feel for the rest of the process. The TL;DR is:

* Add a `beta_settings` -> `cloud_sql_instances` setting to your `app.yaml` that references the instance connection name.
* In the Ecto config, point the socket to `/cloudsql/<instance-connection-name>`.

**Comment by newterminator** [comment]
Wow, amazing, thanks @dazuma for guiding me to help setup postgrex and the corresponding links. I am gonna look at them and get back. Also thanks to @bshaffer for getting the ball rolling with the ecto team.

**Comment by newterminator** [comment]
Hey @chingor13 , I wanted to ask if you could help me out in connecting the Phoenix app on the Flexible App Engine Platform to the Postgresql Cloud SQL instance that I have.

I followed your [code](https://github.com/chingor13/white_elephant/compare/gae) to setup postgrex using ecto github repo but I get the error `[error] Postgrex.Protocol (#PID<0.1986.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (/cloudsql/su**3:us-central1:su**1/.s.PGSQL.5432): no such file or directory - :enoent`

My app.yaml is this:
```
env: flex
runtime: gs://elixir-runtime/elixir.yaml
runtime_config:
  release_app: suapp
beta_settings:
  cloud_sql_instances: su**3:us-central1:su***1
env_variables:
  SECRET_KEY_BASE: kZ**4
  DB_USERNAME: postgres
  DB_PASSWORD: hj**k
  DB_NAME: su**b
```

The config/prod.exs
```
config :suapp, Suapp.Endpoint,
  load_from_system_env: true,
  url: [host: "su**3.appspot.com", port: 8080],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: {:system, "SECRET_KEY_BASE"},
  server: true,
  root: ".",
  version: Mix.Project.config[:version]

config :suapp, Suapp.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: {:system, "DB_USERNAME"},
  password: {:system, "DB_PASSWORD"},
  database: {:system, "DB_NAME"},
  socket: "/cloudsql/su**3:us-central1:su**1",
  pool_size: 20
```

And finally in the mix.exs file I have `{:postgrex, github: "elixir-ecto/postgrex", override: true},`

**Comment by dazuma** [comment]
Just to remove a possibility, make sure you have the sqladmin API enabled. You can check on the cloud console at https://console.cloud.google.com/apis/library/sqladmin.googleapis.com

**Comment by newterminator** [comment]
Hey @dazuma, great catch I hadn't done that and thank you for being helpful in resolving this ... I enabled the api and now I get this error as shown in the screenshot below:
![screen shot 2017-12-02 at 2 00 10 am](https://user-images.githubusercontent.com/5087437/33512834-9a679c56-d704-11e7-8682-9319a515564a.png)

**Comment by dazuma** [comment]
Based on the conversation on the postgrex issue, try pinning postgrex to commit https://github.com/elixir-ecto/postgrex/commit/940c1126a68ad0df065c79980f0fc776ba10633a rather than the master branch.

**Comment by newterminator** [comment]
Hey @dazuma , Thanks for pinning down the exact commit required for it to work - though I am not sure if I got the syntax right - > `{:postgrex, github: "elixir-ecto/postgrex", ref: "940c1126a68ad0df065c79980f0fc776ba10633a", override: true}` as I checked from the [mix documentation](https://hexdocs.pm/mix/Mix.Tasks.Deps.html#module-git-options-git).

Using the above syntax still causes the same error.

**Comment by dazuma** [comment]
Hmm, I'm out of ideas on this one. @chingor13 do you have any ideas?

**Comment by newterminator** [comment]
@dazuma , I just setup a single compute instance with the same app and was able to connect to Cloud SQL database instance using both Cloud SQL Proxy as well as direct IP address connection. 

I apologize in advance, if this is not where I should be posting the following question, since it has nothing to do with the elixir-runtime for App Engine (Flex). 

I wanted to ask though in this [tutorial](https://cloud.google.com/community/tutorials/elixir-phoenix-on-google-compute-engine) - where you mention using docker to deploy Phoenix apps on google compute and then later guide in how to use load balancing to achieve horizontal scaling - could you write up a section on how to achieve (deploy to multiple instances) the same using the OTP releases (using just distillery) which allow to do upgrades without restarting the server. 

Thats how I got the app working on the single instance (without using docker), I'd like to achieve auto horizontal scaling (without the need for docker) on Google Compute Engine.

**Comment by dazuma** [comment]
@newterminator The compute engine tutorial uses docker only to cross-compile (i.e. build an OTP release that will work on the compute engine VMs, even if you build it on your local workstation). It doesn't actually deploy docker containers to compute engine; it gets the executable release out and deploys only the release. Or am I misunderstanding your question?

If you have questions/suggestions/issues on the tutorials, feel free to open issues on the github repo for the tutorials (https://github.com/GoogleCloudPlatform/community). Mention me (@dazuma) on any Elixir-related issues because I don't normally otherwise follow that repo very closely.

**Comment by newterminator** [comment]
Hey @dazuma , thanks so much for following up. Okay now that you mention I do notice that in the steps, you pull out the app.run file and deploy that ... Thanks for making it clear ... so I am going to follow the tutorial steps ... and then if I have any issue use the repo that you mentioned to report anything relevant. 

In the meantime, regarding this issue, I will close it since the postgrex requirement/dependency is not working with the unix sockets.
